language: python
python:
- '3.6'
sudo: required

before_script:
  - pip install matplotlib
  - pip install dm-sonnet
  - pip install python-coveralls
  - pip install pytest-cover
script:
  - chmod +x install.sh
  - ./install.sh
  - py.test --cov-report term --cov=pyodds test/
